project:
  type: book

book:
  title: "Inchainge Agents"
  author: "Christiaan Verhoef"
  date: "14/11/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - Research and Investigation on Model Training and Evaluation for Inchainge Game-Specific AI.md
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



